name = "PlutoTables"
uuid = "e64c0356-fa58-4209-b01c-f6c8ed5474f5"
authors = ["Alexander Plavin <alexander@plav.in>"]
version = "0.1.5"

[deps]
AccessorsExtra = "33016aad-b69d-45be-9359-82a41f556fd4"
CompositionsBase = "a33af91c-f02d-484b-be07-31d278c5ca2b"
DataPipes = "02685ad9-2d12-40c3-9f73-c6aeda6a7ff5"
FlexiMaps = "6394faf6-06db-4fa8-b750-35ccc60383f7"
HypertextLiteral = "ac1192a8-f4b3-4bfe-ba22-af5b92cd3ab2"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"

[weakdeps]
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[extensions]
UnitfulExt = "Unitful"

[compat]
AccessorsExtra = "0.1.45"
CompositionsBase = "0.1.2"
DataPipes = "0.3.8"
FlexiMaps = "0.1.14"
HypertextLiteral = "0.9.4"
PlutoUI = "0.7.51"
julia = "1.9"
